create table SentPayList (
    id BIGINT not null auto_increment,
    customerSegmentGroup BIGINT,
    dayRetryLimitExceededCount integer,
    fetchedTime datetime(6),
    hourRetryLimitExceededCount integer,
    internalErrorCount integer,
    invalidSubscriptionCount integer,
    lastPicked datetime(6),
    noBalanceCount integer,
    noSubscriptionCount integer,
    phone varchar(255),
    pickedStatus bit,
    productId varchar(255),
    serviceId varchar(255),
    spId varchar(255),
    hash varchar(255),
    sentPayId BIGINT,
    successfulCount integer,
    invalidRenewalPeriodCount integer,
    invalidSubscriberStatusCount integer,
    userNotEligibleCount integer,
    unknownErrorCount integer,
    totalNoOfRequestSent integer,
    primary key (id)
) engine=InnoDB;
